name: Code Analysis
on: 
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
jobs:
  basicallyeslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bradennapier/eslint-plus-action@v3.4.0
