name: SA
on:
  pull_request:
    branches:
      - master
jobs:
  analysis:
    name: Files check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          level: error
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: true
          eslint_flags: ". --ext .ts"
